/** @format */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORMS_FAIL = "GET_FORMS_FAIL";

export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWER_SUCCESS = "GET_ANSWER_SUCCESS";
export const GET_ANSWERS_FAIL = "GET_ANSWERS_FAIL";
