/** @format */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORMS_FAIL = "GET_FORMS_FAIL";

export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWER_SUCCESS = "GET_ANSWER_SUCCESS";
export const GET_ANSWERS_FAIL = "GET_ANSWERS_FAIL";

export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";

export const GET_PATIENTS_DOCTOR_SUCCESS = "GET_PATIENTS_DOCTOR_SUCCESS";
export const GET_PATIENTS_DOCTOR_FAIL = "GET_PATIENTS_DOCTOR_FAIL";

export const GET_DOCTORS_SUCCESS = "GET_DOCTORS_SUCCESS";
export const GET_DOCTOR_SUCCESS = "GET_DOCTOR_SUCCESS";
export const GET_DOCTORS_FAIL = "GET_DOCTORS_FAIL";
export const ASSIGN_DOCTOR_SUCCESS = "ASSIGN_DOCTOR_SUCCESS";
export const ASSIGN_DOCTOR_FAIL = "ASSIGN_DOCTOR_FAIL";

export const GET_MESSAGES_PATIENT_SUCCESS = "GET_MESSAGES_PATIENT_SUCCESS";
export const GET_MESSAGES_PATIENT_FAIL = "GET_MESSAGES_PATIENT_FAIL";
export const SEND_MESSAGE_PATIENT_SUCCESS = "SEND_MESSAGE_PATIENT_SUCCESS";
